export const WIN_MESSAGES = [
  "O lucro de hoje é o tijolo do seu castelo de 2026. Não o jogue fora.",
  "Você venceu o algoritmo. Agora vença a sua ganância: SAIA.",
  "Não devolva. O mercado ama quem não sabe parar.",
  "Dinheiro no bolso, mente tranquila. Missão cumprida.",
  "A euforia é mentirosa. Você não é invencível, você apenas seguiu o plano.",
  "Excelente. Agora prove que é profissional e não jogue mais hoje.",
  "O amador continua jogando porque quer emoção. O profissional para porque quer dinheiro.",
  "Meta batida não é meta superada. É meta encerrada.",
  "Guarde esse lucro. Ele é a semente da sua liberdade.",
  "Você operou como um sniper: um tiro, uma morte, retirada.",
  "Sinta o prazer da vitória, mas não se vicie nele.",
  "Sua banca agradece a disciplina. Até amanhã.",
  "Não transforme um dia de glória em um dia de arrependimento.",
  "O segredo da consistência é saber parar quando está ganhando.",
  "Você roubou a casa hoje. Fuja antes que o segurança te pegue.",
  "Lucro bom é lucro protegido. Feche o app.",
  "2026 está um dia mais perto. Continue assim.",
  "A disciplina paga dividendos. Hoje você recebeu o seu.",
  "Não se iluda. O mercado vai tentar te seduzir a devolver tudo.",
  "Inteligência emocional é saber sair da mesa com o bolso cheio.",
  "Você fez o difícil: ganhou. Não faça o estúpido: devolver.",
  "Cada vitória conta. Juros compostos farão o resto.",
  "Hoje você foi o predador. Não vire a presa.",
  "Respeite o seu dinheiro. Ele custou sua atenção e energia.",
  "Vitória limpa. Sem sustos. É assim que se constrói riqueza.",
  "O avião subiu, seu saldo subiu. Agora sua ansiedade deve descer.",
  "Você é um gestor de risco, não um apostador. Bom trabalho.",
  "Amanhã tem mais. Não queira ganhar o mês inteiro em um dia.",
  "Seu 'eu' do futuro agradece por você parar agora.",
  "Isso não é sorte, é método. Mantenha o método.",
  "O mercado financeiro transfere dinheiro dos impacientes para os pacientes. Hoje você foi paciente.",
  "Ganhar é fácil. Difícil é não devolver. Mostre que você consegue.",
  "Bela operação. Agora vá viver a vida fora da tela.",
  "O dinheiro é seu escravo. Hoje ele trabalhou bem.",
  "Não tente a sorte. Você já teve a competência.",
  "A ganância tem olhos grandes e mãos furadas. Cuidado.",
  "Seu saldo aumentou. Sua responsabilidade também.",
  "Parece pouco hoje, mas será milhões em 2026.",
  "A consistência é chata, mas paga viagens de primeira classe.",
  "Você dominou seus impulsos. Essa foi a verdadeira vitória.",
  "Salve o progresso. Game over por hoje. You Win.",
  "O mercado é uma besta selvagem. Você tirou um pedaço dela. Corra.",
  "Orgulhe-se da sua frieza, não apenas do dinheiro.",
  "Um dia de cada vez. A pressa é inimiga da perfeição e da riqueza.",
  "Hoje você operou como o Top 1% do mundo.",
  "Não deixe o sucesso subir à cabeça. Mantenha os pés no chão.",
  "Lucro realizado. Risco zerado. Dia perfeito.",
  "A melhor estratégia agora é: TELA PRETA. Desligue.",
  "Você está construindo um hábito milionário.",
  "Silencie o ego. Agradeça a estratégia. Encerre.",
  "Mais um passo rumo à independência financeira.",
  "O controle emocional é sua maior vantagem competitiva.",
  "Não busque adrenalina. Busque paz e prosperidade.",
  "Você fez o que 99% não conseguem: ganhou e parou.",
  "Sua conta bancária está sorrindo. Não a faça chorar.",
  "Disciplina inabalável. Resultado inevitável.",
  "Hoje o dia é seu. Não dê chance para o azar.",
  "Amanhã o mercado estará lá. Seu lucro pode não estar se você continuar.",
  "Vitória técnica. Sem emoção. Apenas negócios.",
  "Você é o dono do seu destino. E hoje, o destino é lucrar."
];

export const LOSS_MESSAGES = [
  "O Stop Loss é o freio de emergência que salvou sua vida hoje.",
  "Doeu? Ótimo. Use essa dor para focar na disciplina amanhã.",
  "Perder faz parte. Quebrar a banca não. Parabéns por parar.",
  "Não tente recuperar. A vingança é a mãe da falência.",
  "Aceite a derrota de hoje para garantir a vitória da guerra.",
  "O mercado te bateu. Levante, sacuda a poeira e volte amanhã.",
  "Hoje você pagou uma taxa de aprendizado. Aprenda.",
  "Respire. O dinheiro vai e vem. Sua sanidade deve ficar.",
  "Não opere com raiva. O mercado sente cheiro de sangue.",
  "Sua disciplina em parar hoje vale mais que o dinheiro que perdeu.",
  "Um dia ruim não define sua jornada até 2026.",
  "Amanhã é um novo dia. Zere a mente, não a banca.",
  "Engula o choro. O mercado não tem pena de você. Seja forte.",
  "Você tropeçou. Não se jogue no abismo.",
  "O loss é o custo operacional do nosso negócio.",
  "Não cave o buraco mais fundo. Largue a pá.",
  "A vontade de recuperar é um vício. Controle-se.",
  "Feche os olhos. Visualize 2026. Esse loss será irrelevante lá.",
  "Se perdoar é o primeiro passo para recuperar amanhã.",
  "O mercado testou sua fé. Não perca a esperança.",
  "Abaixe a cabeça, aceite o golpe e proteja o que restou.",
  "Não seja um jogador. Seja um gestor de crises.",
  "A derrota ensina mais que a vitória. O que você aprendeu hoje?",
  "Pare agora. Sua mente está tentando te sabotar.",
  "O dinheiro que você não perdeu tentando recuperar é lucro.",
  "Hoje não foi seu dia. Aceite. A humildade enriquece.",
  "O leão recua antes de atacar. Recue hoje.",
  "Não deixe um dia ruim virar uma semana trágica.",
  "Sua banca ainda está viva. Você ainda está no jogo.",
  "Controle o desespero. O desespero atrai a derrota.",
  "Esqueça o valor financeiro. Foque no erro técnico.",
  "Você não é suas perdas. Você é sua disciplina.",
  "Vá dormir. Amanhã com a cabeça fria você verá melhor.",
  "Não persiga o prejuízo. Ele corre mais rápido que você.",
  "A resiliência é forjada no fogo da derrota.",
  "Se você continuar, vai perder o dobro. É matemática.",
  "Honre seu Stop Loss. Ele é seu melhor amigo.",
  "A dor passa. O arrependimento de quebrar a banca fica.",
  "Hoje o mercado venceu a batalha. A guerra continua.",
  "Saia da tela. Vá fazer algo que te dê prazer.",
  "Não se puna. Apenas corrija a rota.",
  "Todo trader de elite já passou por isso. Continue.",
  "O fracasso é apenas um degrau. Não pare de subir.",
  "Mantenha a cabeça erguida. O jogo vira.",
  "Seu sistema funciona. O mercado que é soberano.",
  "Proteja seu capital psicológico. Pare agora.",
  "Não deixe o ego te falir. Aceite que errou.",
  "Amanhã haverá novas oportunidades. Esteja vivo para elas.",
  "O loss testa quem realmente quer ser rico.",
  "Limpe as lágrimas e afie o machado para amanhã.",
  "Você perdeu dinheiro, não sua capacidade.",
  "Disciplina é fazer o que precisa ser feito, mesmo doendo.",
  "Não entregue sua vida por causa de um dia vermelho.",
  "Respeite o ciclo. Dias de luta, dias de glória.",
  "Foque no longo prazo. Esse dia será apenas um borrão.",
  "Seja frio. A emoção é sua inimiga agora.",
  "Pare. Respire. Recalcule. Amanhã execute.",
  "A consistência inclui saber perder pouco.",
  "Não jogue o resto fora. Amanhã você vai precisar.",
  "Você vai recuperar. Mas não hoje. Acredite."
];

export const NEUTRAL_MESSAGES = [
  "O zero a zero é uma vitória defensiva. Capital protegido.",
  "Sobreviver é a regra número 1. Você sobreviveu.",
  "Nem ganhar, nem perder. Hoje foi dia de treinar a paciência.",
  "Empatar no mercado é melhor que perder na poupança.",
  "Sua banca continua intacta. Oportunidade preservada.",
  "Um dia sem perdas é um bom dia.",
  "Amanhã buscaremos o lucro. Hoje garantimos a segurança.",
  "Paciência. O sniper espera o momento certo.",
  "Você não entregou nada para o mercado. Isso é bom.",
  "Frieza e cálculo. Hoje foi um empate técnico."
];